version: "3.5"
services:
  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: elasticsearch
    restart: on-failure
    environment:
      - "discovery.type=single-node"
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch
    ports:
      - 9200:9200

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: on-failure
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - /data/mysql/conf:/etc/mysql/conf.d
      - /data/mysql/logs:/var/log/mysql
      - /data/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306


    



