version: "3.5"
services:
  elasticsearch:
    image: elasticsearch:7.9.0
    container_name: elastic
    restart: on-failure
    environment:
      - "discovery.type=single-node"
    volumes:
      - /j/elasticsearch/config:/usr/share/elasticsearch/config
      - /j/elasticsearch/data:/usr/share/elasticsearch/data
      - /j/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200

#  kibana:
#    depends_on:
#      - elasticsearch
#    image: kibana:7.9.0
#    container_name: kibana
#    restart: no
#    volumes:
#      - /j/kibana/config:/usr/share/kibana/config
#    ports:
#      - 5601:5601

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: on-failure
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - /j/mysql/conf:/etc/mysql/conf.d
      - /j/mysql/logs:/var/log/mysql
      - /j/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306


    



